[package]
name = "massive-layout"
version = "0.1.0"
edition.workspace = true

[dependencies]
massive-geometry = { workspace = true }
massive-util = { workspace = true }

euclid.workspace = true
derive_more.workspace = true
