[package]
name = "massive-geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
flo_curves = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
cgmath = { workspace = true }
