[package]
name = "desktop"
version = "0.1.0"
edition.workspace = true

[dependencies]
massive-shell.workspace = true
massive-applications.workspace = true

anyhow.workspace = true
derive_more.workspace = true
tokio.workspace = true
uuid.workspace = true
